
CREATE DATABASE IF NOT EXISTS OtakuShop;

USE OtakuShop;

CREATE TABLE USUARIOS(
	`ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(100) NOT NULL,
    `SENHA` VARCHAR(64)  NOT NULL,
    `NOME`  VARCHAR(100) DEFAULT NULL,
    `USUARIO` VARCHAR(50) NOT NULL,
    `NASCIMENTO`VARCHAR(12) DEFAULT NULL,
    `TELEFONE` VARCHAR(20) DEFAULT NULL,
    `CEP` VARCHAR(10) DEFAULT NULL,
    `ESTADO` VARCHAR(3) DEFAULT NULL,
    `RUA` VARCHAR(120) DEFAULT NULL,
    `NUMERO` VARCHAR(5) DEFAULT NULL,
    `CIDADE` VARCHAR(50) DEFAULT NULL,
    `COMPLEMENTO` TEXT DEFAULT NULL,
    `BAIRRO`  VARCHAR(50) DEFAULT NULL,
    `PATH`    VARCHAR(120) DEFAULT NULL,
    PRIMARY KEY(`ID_USUARIO`)
);
CREATE TABLE ANIMES(
 `ID_ANIME` int NOT NULL AUTO_INCREMENT,
 `NOME` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`ID_ANIME`)
);

CREATE TABLE CLASSES(
	`ID_CLASSE` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(25) NOT NULL,
     PRIMARY KEY(`ID_CLASSE`)
);
CREATE TABLE PRODUTOS(
 `ID_PRODUTO` int NOT NULL AUTO_INCREMENT,
 `PATH` varchar(80) DEFAULT NULL, 
 `NOME` varchar(80) DEFAULT NULL,
 `PRECO` FLOAT DEFAULT NULL,
 `ID_CLASSE` INT DEFAULT NULL, 
 `DESC1` TEXT DEFAULT NULL,
 `DESC2` TEXT DEFAULT NULL, 
 `DESC3` TEXT DEFAULT NULL,
 `ISSIZE` INT DEFAULT NULL,
 `ESTOQUE`INT DEFAULT NULL, 
 `DEFAULTSIZE` varchar(3) DEFAULT NULL,
 `SIZES` varchar(15) DEFAULT NULL,
 `ID_ANIME` INT DEFAULT NULL,
 PRIMARY KEY (`ID_PRODUTO`),
 FOREIGN KEY (ID_CLASSE) REFERENCES CLASSES(ID_CLASSE),
 FOREIGN KEY (ID_ANIME)  REFERENCES ANIMES(ID_ANIME)
);
CREATE TABLE CARRINHO(
	`ID_CARRINHO` INT NOT NULL AUTO_INCREMENT,
    `ID_PRODUTO`  INT NOT NULL,
    `ID_USUARIO`  INT NOT NULL,
    `QUANT`       INT NOT NULL,
    `SIZE`        VARCHAR(5) NOT NULL,
     PRIMARY KEY(`ID_CARRINHO`),
     FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
     FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
CREATE TABLE SESSIONS(
	`ID_SESSION` INT NOT NULL AUTO_INCREMENT,
    `ID_USUARIO` INT NOT NULL,
    `TOKEN` VARCHAR(500) DEFAULT NULL,
     PRIMARY KEY(`ID_SESSION`),
     FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
CREATE TABLE DESTAQUES(
	`ID_DESTAQUE` INT NOT NULL AUTO_INCREMENT,
    `ID_PRODUTO` INT DEFAULT NULL,
     PRIMARY KEY (`ID_DESTAQUE`),
     FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);
CREATE TABLE CATEGORIA_CUPOM(
   `ID_CATEGORIA`  INT NOT NULL AUTO_INCREMENT,
   `CATEGORIA`     VARCHAR(20),
	PRIMARY KEY (`ID_CATEGORIA`)
);
CREATE TABLE TIPO_CUPOM(
   `ID_TIPO`  INT NOT NULL AUTO_INCREMENT,
   `TIPO_CUPOM`     VARCHAR(20),
	PRIMARY KEY (`ID_TIPO`)
);
CREATE TABLE STATUS_CUPOM(
   `ID_STATUS`  INT NOT NULL AUTO_INCREMENT,
   `STATUS`     VARCHAR(20),
	PRIMARY KEY (`ID_STATUS`)
);

CREATE TABLE CUPONS(
   `ID_CUPOM`     INT NOT NULL AUTO_INCREMENT,
   `CUPOM`        VARCHAR(10),
   `ID_CATEGORIA` INT NOT NULL,
   `ID_TIPO`      INT NOT NULL,
   `VALOR`        REAL,
   `ID_STATUS`    INT NOT NULL,
	PRIMARY KEY (`ID_CUPOM`),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_CUPOM(ID_CATEGORIA),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CUPOM(ID_TIPO),
    FOREIGN KEY (ID_STATUS) REFERENCES STATUS_CUPOM(ID_STATUS)
);

CREATE TABLE CUPONS_RESGATADOS(
   `ID_CUPOM_RES`     INT NOT NULL AUTO_INCREMENT,
   `ID_USUARIO`     INT NOT NULL,
   `ID_CUPOM`     INT NOT NULL,
   PRIMARY KEY(ID_CUPOM_RES),
   FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
   FOREIGN KEY (ID_CUPOM) REFERENCES CUPONS(ID_CUPOM)
);